name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create build dir
      run: mkdir ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ../src

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./unittests
